use_frameworks!

platform :ios, '9.0'

target 'HUPodTest2_Example' do
  pod 'HUPodTest2', :path => '../'

  target 'HUPodTest2_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
